### ISSUE TITLE
website: local development issue

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/waku#344]
- [x] ~I notice a flash of unstyled content (FOUC) on save. (reported by @sandren)~ #414 mitigates it. 👉 #427
- [x] ~https://github.com/dai-shi/waku/pull/345/files#r1440484445~ #364 fixes it.
- [x] ~prop mismatch error with ssr https://github.com/dai-shi/waku/pull/364#issuecomment-1888505712~ #426
- [ ] initial page load is very slow (~10s)
- [ ] event handler sometimes fails with HMR https://github.com/dai-shi/waku/issues/344#issuecomment-1890323113

**Comment by dai-shi** [comment]
@Aslemammad you might be interested in taking this.

**Comment by Aslemammad** [comment]
Yep, I might have some ideas.

**Comment by sandren** [comment]
Event handlers are sometimes failing after page reload or HMR until the dev server is restarted.

**Comment by ojj1123** [comment]
> I notice a flash of unstyled content (FOUC) on save.

I would like to try to track this issue

**Comment by dai-shi** [comment]
https://github.com/dai-shi/waku/issues/113#issuecomment-1902528306

@ojj1123 In the mean time, how about you taking a look at this? 
> initial page load is very slow (~10s)

**Comment by ojj1123** [comment]
> @ojj1123 In the mean time, how about you taking a look at this?

Okay. This warning message was shown also to me.
